SCREEN_W, SCREEN_H = 1024, 700
FPS = 60
CARD_WIDTH, CARD_HEIGHT = 100, 140
MARGIN = 20
TABLEAU_X = [MARGIN + i*(CARD_WIDTH+20) for i in range(7)]
TABLEAU_Y = 170
FOUNDATION_X = [MARGIN + i*(CARD_WIDTH+20) for i in range(4)]
FOUNDATION_Y = MARGIN
STOCK_POS = (SCREEN_W - CARD_WIDTH - MARGIN, MARGIN)
WASTE_POS = (SCREEN_W - CARD_WIDTH - MARGIN - (CARD_WIDTH+10), MARGIN)

SUITS = ['S','H','D','C']
RANKS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
COLOR_OF_SUIT = {'S':'B','C':'B','H':'R','D':'R'}
